name = "ogp-generator"
compatibility_date = "2024-10-11"
main = "./dist/bundle.js"

[[r2_buckets]]
binding = "MY_R2_BUCKET"
bucket_name = "ogp-storage"

[observability]
enabled = true

[wasm_modules]
"CANVAS_MANAGER_WASM" = "./src/tiny-skia/pkg/canvas_manager_wasm_bg.wasm"